// <auto-generated />
using System;
using FinTech.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinTech.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516142020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinTech.Domain.Entidades.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Term")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.24m,
                            LoanType = "Fixed",
                            MonthlyIncome = 3000m,
                            MonthlyPayment = 467.26m,
                            Status = "Active",
                            Term = 12,
                            UpdatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-001"
                        });
                });

            modelBuilder.Entity("FinTech.Domain.Entidades.PaymentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("PaymentSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 90.44m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 1,
                            Principal = 376.82m,
                            RemainingBalance = 4623.18m,
                            Status = "Paid",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000002-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 83.62m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 2,
                            Principal = 383.64m,
                            RemainingBalance = 4239.54m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000003-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 76.68m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 3,
                            Principal = 390.58m,
                            RemainingBalance = 3848.96m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000004-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 69.62m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 4,
                            Principal = 397.64m,
                            RemainingBalance = 3451.32m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000005-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 62.43m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 5,
                            Principal = 404.83m,
                            RemainingBalance = 3046.49m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000006-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 55.10m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 6,
                            Principal = 412.16m,
                            RemainingBalance = 2634.33m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000007-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 47.65m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 7,
                            Principal = 419.61m,
                            RemainingBalance = 2214.72m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000008-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 40.06m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 8,
                            Principal = 427.20m,
                            RemainingBalance = 1787.52m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000009-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 32.33m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 9,
                            Principal = 434.93m,
                            RemainingBalance = 1352.59m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000010-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 24.47m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 10,
                            Principal = 442.79m,
                            RemainingBalance = 909.80m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000011-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 16.46m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 11,
                            Principal = 450.80m,
                            RemainingBalance = 459.00m,
                            Status = "Pending",
                            TotalPayment = 467.26m
                        },
                        new
                        {
                            Id = new Guid("c0000012-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 8.30m,
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PaymentNumber = 12,
                            Principal = 459.00m,
                            RemainingBalance = 0.00m,
                            Status = "Pending",
                            TotalPayment = 467.30m
                        });
                });

            modelBuilder.Entity("FinTech.Domain.Entidades.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("LoanId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7890-abcd-ef1234567890"),
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desembolso préstamo aprobado",
                            IdempotencyKey = "disbursement-a1b2c3d4",
                            LoanId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Status = "Completed",
                            Type = "Disbursement"
                        });
                });

            modelBuilder.Entity("FinTech.Domain.Entidades.PaymentSchedule", b =>
                {
                    b.HasOne("FinTech.Domain.Entidades.Loan", "Loan")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("FinTech.Domain.Entidades.Transaction", b =>
                {
                    b.HasOne("FinTech.Domain.Entidades.Loan", "Loan")
                        .WithMany("Transactions")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("FinTech.Domain.Entidades.Loan", b =>
                {
                    b.Navigation("PaymentSchedules");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
